### ISSUE TITLE
Brainstorm secret ideas. What do the snitches know?

### ISSUE THREAD

**Issue by TyeBryant** [njramage/SilenceTheSnitch#21]

**Comment by njramage** [comment]
Add ideas as comments

**Comment by LeLionDev** [comment]
We could 'show' the player what crime the player has committed through a slot machine type. I'll draft up a quick mock of what it would look like. Then because the player them selves is aware of the types of 'crime elements' of the crime, the snitches then know the types of elements that are now linked to the crime?

e.g. slot machine shows physical [type of crime], knife [tools], blood [bilogical], picture [digital]

now snitches knows
- player was at the scene
- player used some sort of tool
- saw player get hurt around the table
- have a picture of the fight 

For the player, they'll always be given 2 types of card at the beginning of the game.
- talk
- informant

Essentially the first move is always talk to the informant which gives the first clue. This also shows to players that informant has limited usages. The clue however can be anything. Depending on how we want to go about it, but for this example, let's say it gave a physical place card (parking lot).

The player now has a choice, combine the talk card with parking lot which then gives another random clue, or combine the informant with the parking lot which gives out a better clue than usual (marked with a different colour perhaps).

For this example, let's say the player combined the talk and parking lot. These two combination is a talk + physical location card, which gives out an information card. The information says the person we're after may have been parked at the parking lot (or not) and gives out an information card.

The information card now can be combined with any of the existing cards. For this example, let's say the information card is now combined with informant card.

Informant says he/she heard there was a person that might've witnessed the crime. The person of interest was wearing a blue jacket (or something common/feature of the snitches rostered in the snitch section)

and the game continues.

The combination of cards can be:
- talk/poke/anything we want for the 'interaction card' to be.
- informant limited usages per game (unless we want to add a way refill/resource for additional usages)
- physical locations (e.g. parking lot, convenient store, etc) pretty much anything we think of a good crime scenario involvement that can also be used as a location/information card.
- tools (e.g. knife, golf clubs, shopping bag, plastic bag) pretty much anything we think of a good weapon based on the crime scenario we think of.
- information card (e.g. the card itself is a wild card and is going to pull out either information about the snitch or a 'lead' to follow next).
- evidence (e.g. blood, pictures, digital recording, sightings) this card can be used both ways, if the player uses the 'talk' card with the evidence card, it'll combine to another evidence card with some story about what it might be from. The only way to get a direct link between the 'evidence' card and the smith is by combining them with informant. However Informant has limited usages which needs a bit of thinking before hand.

couldn't think of anymore combinations. I'll add on if people find this favourable.

**Comment by njramage** [comment]
Closing this we now have a storyboard https://docs.google.com/document/d/10q50XOLaP9kbUiRT_XSfFPBM2i185VxwfjzLaGzYFoQ/edit?usp=sharing
